-- =============================================================================
-- V12: Relación N:M entre ejes_tematicos y niveles (grados 1 a 6)
--
-- Problema que resuelve:
--   Hasta esta versión, el wizard de evaluación por saber mostraba los mismos
--   7 ejes temáticos para cualquier grado, sin considerar el currículo MEP.
--   Por ejemplo: "Álgebra y patrones" aparecía evaluable para un estudiante
--   de 1° grado, cuando en el currículo costarricense solo se introduce desde
--   4° en adelante.
--
-- Solución elegida (M:N):
--   Tabla puente `ejes_tematicos_niveles` que indica qué ejes aplican a qué
--   grado. Un eje puede pertenecer a múltiples grados (escenario normal,
--   con distinta profundidad). Esto evita duplicar 21 ejes × 6 grados.
--
--   Alternativa descartada: agregar `nivel_id` directamente en ejes_tematicos.
--   Implicaba duplicar cada eje para cada grado y rompía las claves únicas
--   existentes por (materia, tipo_saber, orden).
--
-- Seed inicial (basado en currículo MEP CR para Primaria):
--   - ESPAÑOL: los 21 ejes aplican a 1°-6° (lengua materna progresiva).
--   - CIENCIAS / ESTUDIOS SOCIALES: 21 ejes en 1°-6° (transversales).
--   - MATEMÁTICAS: filtrado por bloque temático real del currículo:
--       * Números, Geometría, Resolución, Razonamiento → 1°-6°
--       * Estadística                                  → 3°-6°
--       * Fracciones / decimales / porcentajes         → 3°-6°
--       * Álgebra y patrones                           → 4°-6°
--   - EDUCACIÓN FÍSICA: ejes 1°-6° si existen (no se evalúa por saber por
--     ahora, pero la regla queda preparada).
--
-- El admin (o una migración posterior) puede refinar estas asignaciones según
-- lineamientos específicos del MEP. La tabla soporta cualquier combinación.
-- =============================================================================

CREATE TABLE ejes_tematicos_niveles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eje_tematico_id INTEGER NOT NULL
                        REFERENCES ejes_tematicos(id) ON DELETE CASCADE,
    nivel_id        BIGINT NOT NULL
                        REFERENCES niveles(id) ON DELETE CASCADE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_eje_nivel UNIQUE (eje_tematico_id, nivel_id)
);

CREATE INDEX idx_eje_nivel_eje   ON ejes_tematicos_niveles(eje_tematico_id);
CREATE INDEX idx_eje_nivel_nivel ON ejes_tematicos_niveles(nivel_id);

COMMENT ON TABLE ejes_tematicos_niveles IS
    'Relación N:M entre ejes temáticos y niveles educativos. Define qué ejes son evaluables en cada grado.';

-- ===========================================================================
-- SEED: asignaciones por defecto (currículo MEP CR Primaria)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1) ESPAÑOL — todos los ejes (21) aplican a todos los grados (1°-6°)
-- ---------------------------------------------------------------------------
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'ESPANOL'
  AND n.numero_grado BETWEEN 1 AND 6
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2) CIENCIAS — todos los ejes (21) aplican a todos los grados (1°-6°)
-- ---------------------------------------------------------------------------
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'CIENCIAS'
  AND n.numero_grado BETWEEN 1 AND 6
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3) ESTUDIOS SOCIALES — todos los ejes (21) aplican a todos los grados
-- ---------------------------------------------------------------------------
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'ESTUDIOS_SOCIALES'
  AND n.numero_grado BETWEEN 1 AND 6
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4) MATEMÁTICAS — filtrado por bloque temático
-- ---------------------------------------------------------------------------

-- 4a) Bloques presentes en TODOS los grados (1°-6°)
--     Números, Geometría, Resolución de problemas, Razonamiento
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'MATEMATICAS'
  AND n.numero_grado BETWEEN 1 AND 6
  AND e.clave IN (
      'MC_NUMEROS',      'MP_NUMEROS',      'MA_NUMEROS',
      'MC_GEOMETRIA',    'MP_GEOMETRIA',    'MA_GEOMETRIA',
      'MC_PROBLEMAS',    'MP_PROBLEMAS',    'MA_PROBLEMAS',
      'MC_RAZONAMIENTO', 'MP_RAZONAMIENTO', 'MA_RAZONAMIENTO'
  )
ON CONFLICT DO NOTHING;

-- 4b) Fracciones, decimales y porcentajes — desde 3° en adelante
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'MATEMATICAS'
  AND n.numero_grado BETWEEN 3 AND 6
  AND e.clave IN ('MC_FRACCIONES', 'MP_FRACCIONES', 'MA_FRACCIONES')
ON CONFLICT DO NOTHING;

-- 4c) Estadística y probabilidad — desde 3° en adelante (nociones básicas)
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'MATEMATICAS'
  AND n.numero_grado BETWEEN 3 AND 6
  AND e.clave IN ('MC_ESTADISTICA', 'MP_ESTADISTICA', 'MA_ESTADISTICA')
ON CONFLICT DO NOTHING;

-- 4d) Álgebra y patrones — desde 4° en adelante
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'MATEMATICAS'
  AND n.numero_grado BETWEEN 4 AND 6
  AND e.clave IN ('MC_ALGEBRA', 'MP_ALGEBRA', 'MA_ALGEBRA')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 5) EDUCACIÓN FÍSICA — todos los ejes existentes aplican a 1°-6°
--    (si la materia no tiene ejes registrados aún, este INSERT no afecta nada)
-- ---------------------------------------------------------------------------
INSERT INTO ejes_tematicos_niveles (eje_tematico_id, nivel_id)
SELECT e.id, n.id
FROM ejes_tematicos e
JOIN materias m ON m.id = e.materia_id
CROSS JOIN niveles n
WHERE m.clave = 'EDUCACION_FISICA'
  AND n.numero_grado BETWEEN 1 AND 6
ON CONFLICT DO NOTHING;

-- ===========================================================================
-- Vista de apoyo para consultas frontales (qué ejes aplican a una materia + nivel)
-- ===========================================================================
CREATE OR REPLACE VIEW vw_ejes_por_materia_nivel AS
SELECT
    en.nivel_id,
    n.numero_grado,
    e.materia_id,
    m.clave    AS materia_clave,
    m.nombre   AS materia_nombre,
    e.tipo_saber_id,
    ts.clave   AS tipo_saber_clave,
    ts.nombre  AS tipo_saber_nombre,
    e.id       AS eje_id,
    e.clave    AS eje_clave,
    e.nombre   AS eje_nombre,
    e.orden    AS eje_orden
FROM ejes_tematicos_niveles en
JOIN ejes_tematicos e ON e.id = en.eje_tematico_id
JOIN niveles n        ON n.id = en.nivel_id
JOIN materias m       ON m.id = e.materia_id
JOIN tipos_saber ts   ON ts.id = e.tipo_saber_id;

COMMENT ON VIEW vw_ejes_por_materia_nivel IS
    'Catálogo plano de ejes filtrables por materia, tipo de saber y nivel/grado.';
