-- =============================================================================
-- V14: Verificación de email + reset de contraseña por código
--
-- Dos features nuevos relacionados:
--
-- 1. VERIFICACIÓN DE EMAIL
--    Cuando un admin crea un usuario, se le envía un correo con un link
--    de verificación. El usuario puede iniciar sesión sin verificar (modo
--    "soft": solo aparece un banner avisando), pero algunas acciones futuras
--    podrían requerirlo. Los usuarios sembrados en V2 quedan marcados como
--    verificados (son reales, no necesitan validar).
--
-- 2. RESET DE CONTRASEÑA POR CÓDIGO
--    El usuario olvidó su contraseña → pide reset desde el login → recibe
--    un código de 6 dígitos en su correo → ingresa código + nueva contraseña.
--    Códigos expiran rápido (15 min) y son de un solo uso.
--
-- Ambos casos se modelan con la misma tabla `email_tokens` distinguidos por
-- la columna `tipo`. El payload se guarda hasheado (SHA-256), nunca en texto
-- plano — igual que como ya se manejan los refresh tokens.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) Columna email_verificado en usuarios
-- ---------------------------------------------------------------------------
ALTER TABLE usuarios
    ADD COLUMN email_verificado BOOLEAN NOT NULL DEFAULT FALSE;

-- Los usuarios sembrados en V2 son reales (admin@atara, mgarcia, jperez,
-- avargas, keylor). No necesitan flujo de verificación.
UPDATE usuarios SET email_verificado = TRUE;

-- ---------------------------------------------------------------------------
-- 2) Tabla email_tokens
-- ---------------------------------------------------------------------------
-- token_hash: SHA-256 del valor que se manda por correo (para verificación
--   es un UUID, para reset es el código de 6 dígitos). Nunca guardamos el
--   valor en texto plano para que un dump de BD no permita usar tokens
--   pendientes.
-- tipo: VERIFICACION_EMAIL | RESET_PASSWORD
-- usado_en: NULL si está pendiente; timestamp cuando se redime. Un token
--   usado no se puede volver a usar.
-- expira_en: vencimiento absoluto. Verificación 24h, reset 15min.
CREATE TABLE email_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INTEGER NOT NULL
                    REFERENCES usuarios(id) ON DELETE CASCADE,
    tipo        VARCHAR(30) NOT NULL
                    CONSTRAINT chk_email_token_tipo
                    CHECK (tipo IN ('VERIFICACION_EMAIL', 'RESET_PASSWORD')),
    token_hash  VARCHAR(64) NOT NULL,
    expira_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    usado_en    TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_email_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_email_tokens_usuario ON email_tokens(usuario_id);
CREATE INDEX idx_email_tokens_tipo    ON email_tokens(tipo);
-- Búsqueda rápida de tokens pendientes al limpiar/expirar
CREATE INDEX idx_email_tokens_pendientes ON email_tokens(expira_en) WHERE usado_en IS NULL;

COMMENT ON TABLE email_tokens IS
    'Tokens de un solo uso para verificación de email y reset de contraseña. Guardados como SHA-256 del valor enviado por correo.';
