-- =============================================================================
-- ATARA — Migraciones consolidadas
-- =============================================================================
-- Consolidación de las migraciones originales V1..V26 en su ESTADO FINAL — solo el esquema (estructura). Generado
-- con pg_dump y validado: esquema (tablas/indices/FK/constraints/triggers/funciones/
-- vistas) y conteos de filas IDÉNTICOS al resultado de aplicar las 26 migraciones.
-- ADVERTENCIA: no aplicar sobre una BD que ya ejecutó las migraciones originales
-- (rompe el historial de Flyway). Es para entornos nuevos / versión limpia.
-- =============================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fn_actualizar_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_actualizar_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


--
-- Name: FUNCTION fn_actualizar_updated_at(); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.fn_actualizar_updated_at() IS 'Asigna updated_at = NOW() antes de cada UPDATE.';


--
-- Name: fn_eval_saber_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_eval_saber_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alertas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alertas (
    id integer NOT NULL,
    estudiante_id integer NOT NULL,
    contenido_id integer NOT NULL,
    periodo_id integer NOT NULL,
    config_alerta_id integer NOT NULL,
    evaluacion_id integer,
    generada_por integer,
    tipo_alerta character varying(20) NOT NULL,
    nivel_alerta character varying(10) NOT NULL,
    motivo text NOT NULL,
    estado character varying(15) DEFAULT 'ACTIVA'::character varying NOT NULL,
    fecha_generacion timestamp with time zone DEFAULT now() NOT NULL,
    fecha_resolucion timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_alerta_estado CHECK (((estado)::text = ANY ((ARRAY['ACTIVA'::character varying, 'RESUELTA'::character varying, 'DESCARTADA'::character varying])::text[]))),
    CONSTRAINT chk_alerta_nivel CHECK (((nivel_alerta)::text = ANY ((ARRAY['BAJO'::character varying, 'MEDIO'::character varying, 'ALTO'::character varying])::text[]))),
    CONSTRAINT chk_alerta_resolucion CHECK (((((estado)::text = 'ACTIVA'::text) AND (fecha_resolucion IS NULL)) OR (((estado)::text = ANY ((ARRAY['RESUELTA'::character varying, 'DESCARTADA'::character varying])::text[])) AND (fecha_resolucion IS NOT NULL)))),
    CONSTRAINT chk_alerta_tipo CHECK (((tipo_alerta)::text = ANY ((ARRAY['PREVENTIVA'::character varying, 'MODERADA'::character varying, 'CRITICA'::character varying])::text[])))
);


--
-- Name: TABLE alertas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.alertas IS 'Alertas de riesgo académico, manuales o generadas por el motor de reglas.';


--
-- Name: COLUMN alertas.evaluacion_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.alertas.evaluacion_id IS 'NULL para alertas manuales. Permite trazar qué evaluación originó la alerta.';


--
-- Name: alertas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alertas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alertas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alertas_tematicas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alertas_tematicas (
    id bigint NOT NULL,
    estudiante_id bigint NOT NULL,
    periodo_id bigint NOT NULL,
    eje_tematico_id integer NOT NULL,
    promedio numeric(4,2) NOT NULL,
    nivel_alerta character varying(15) NOT NULL,
    motivo text NOT NULL,
    estado character varying(15) DEFAULT 'ACTIVA'::character varying NOT NULL,
    generada_por bigint,
    fecha_generacion timestamp with time zone DEFAULT now() NOT NULL,
    fecha_resolucion timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    materia_id integer NOT NULL,
    seccion_id bigint NOT NULL,
    CONSTRAINT chk_estado_alerta_tem CHECK (((estado)::text = ANY ((ARRAY['ACTIVA'::character varying, 'RESUELTA'::character varying, 'DESCARTADA'::character varying])::text[]))),
    CONSTRAINT chk_nivel_alerta_tem CHECK (((nivel_alerta)::text = ANY ((ARRAY['ALTA'::character varying, 'MEDIA'::character varying, 'SIN_ALERTA'::character varying])::text[])))
);


--
-- Name: TABLE alertas_tematicas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.alertas_tematicas IS 'Alertas generadas automáticamente a partir de promedios por eje temático en un periodo.';


--
-- Name: alertas_tematicas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alertas_tematicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alertas_tematicas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anios_lectivos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anios_lectivos (
    id integer NOT NULL,
    anio smallint NOT NULL,
    activo boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_anio_rango CHECK (((anio >= 2000) AND (anio <= 2200)))
);


--
-- Name: TABLE anios_lectivos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.anios_lectivos IS 'Año escolar (ej. 2025). Solo uno puede estar activo.';


--
-- Name: COLUMN anios_lectivos.activo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.anios_lectivos.activo IS 'TRUE = año en curso. Índice parcial garantiza unicidad.';


--
-- Name: anios_lectivos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anios_lectivos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anios_lectivos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: centros_educativos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.centros_educativos (
    id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    circuito character varying(10),
    direccion_regional character varying(100),
    telefono character varying(20),
    correo character varying(150),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE centros_educativos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.centros_educativos IS 'Escuelas primarias registradas en el sistema. Quedaria abierto para que agreguen las necesarias';


--
-- Name: centros_educativos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.centros_educativos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.centros_educativos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion_alertas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_alertas (
    id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    umbral_minimo numeric(5,2),
    umbral_maximo numeric(5,2),
    tipo_alerta character varying(20) NOT NULL,
    nivel_resultante character varying(10) NOT NULL,
    dimension_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_config_nivel_resultante CHECK (((nivel_resultante)::text = ANY ((ARRAY['BAJO'::character varying, 'MEDIO'::character varying, 'ALTO'::character varying])::text[]))),
    CONSTRAINT chk_config_tipo_alerta CHECK (((tipo_alerta)::text = ANY ((ARRAY['PREVENTIVA'::character varying, 'MODERADA'::character varying, 'CRITICA'::character varying])::text[])))
);


--
-- Name: TABLE configuracion_alertas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.configuracion_alertas IS 'Reglas del motor de alertas tempranas con rangos de umbral.';


--
-- Name: COLUMN configuracion_alertas.dimension_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.configuracion_alertas.dimension_id IS 'NULL = regla aplica al promedio global del estudiante.';


--
-- Name: configuracion_alertas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configuracion_alertas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_alertas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contenidos (
    id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    materia_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE contenidos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.contenidos IS 'Unidades temáticas dentro de cada materia.';


--
-- Name: contenidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contenidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contenidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: criterios_indicadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.criterios_indicadores (
    id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    contenido_id integer NOT NULL,
    dimension_id integer NOT NULL,
    peso numeric(5,2) DEFAULT 1.0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_criterio_peso CHECK ((peso > (0)::numeric))
);


--
-- Name: TABLE criterios_indicadores; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.criterios_indicadores IS 'Ítems observables evaluados con escala Likert 1-4.';


--
-- Name: COLUMN criterios_indicadores.dimension_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.criterios_indicadores.dimension_id IS 'Obligatorio. Dimensión de evaluación a la que pertenece el criterio.';


--
-- Name: criterios_indicadores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.criterios_indicadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.criterios_indicadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_evaluacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_evaluacion (
    id integer NOT NULL,
    evaluacion_id integer NOT NULL,
    criterio_id integer NOT NULL,
    escala_id integer NOT NULL,
    observacion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE detalle_evaluacion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.detalle_evaluacion IS '3NF: solo criterio_id y escala_id. valor_numerico se obtiene via JOIN con escalas_valoracion.';


--
-- Name: detalle_evaluacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_evaluacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_evaluacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_evaluacion_saber; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalle_evaluacion_saber (
    id bigint NOT NULL,
    evaluacion_saber_id bigint NOT NULL,
    eje_tematico_id integer NOT NULL,
    valor smallint NOT NULL,
    observacion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_detalle_valor CHECK (((valor >= 1) AND (valor <= 5)))
);


--
-- Name: TABLE detalle_evaluacion_saber; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.detalle_evaluacion_saber IS 'Valor asignado a cada eje temático dentro de una evaluación por saber.';


--
-- Name: detalle_evaluacion_saber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalle_evaluacion_saber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_evaluacion_saber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dimensiones_evaluacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dimensiones_evaluacion (
    id integer NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text,
    peso numeric(5,2) DEFAULT 1.0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_dimension_peso CHECK ((peso > (0)::numeric))
);


--
-- Name: TABLE dimensiones_evaluacion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.dimensiones_evaluacion IS 'Ejes de evaluación: Rendimiento Académico, Participación, Hábitos, Socioemocional, Asistencia.';


--
-- Name: COLUMN dimensiones_evaluacion.peso; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.dimensiones_evaluacion.peso IS 'Peso relativo al calcular promedios ponderados.';


--
-- Name: dimensiones_evaluacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dimensiones_evaluacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dimensiones_evaluacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ejes_tematicos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ejes_tematicos (
    id integer NOT NULL,
    tipo_saber_id integer NOT NULL,
    clave character varying(30) NOT NULL,
    nombre character varying(500) NOT NULL,
    descripcion text,
    orden smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    materia_id integer NOT NULL,
    periodo_numero smallint,
    CONSTRAINT chk_ejes_tematicos_periodo CHECK (((periodo_numero IS NULL) OR ((periodo_numero >= 1) AND (periodo_numero <= 3))))
);


--
-- Name: TABLE ejes_tematicos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ejes_tematicos IS 'Ejes temáticos de evaluación, 7 por cada tipo de saber (21 total).';


--
-- Name: COLUMN ejes_tematicos.periodo_numero; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ejes_tematicos.periodo_numero IS 'Trimestre asociado al eje (1, 2, 3). NULL = aplicable a cualquier trimestre.';


--
-- Name: ejes_tematicos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ejes_tematicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ejes_tematicos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ejes_tematicos_niveles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ejes_tematicos_niveles (
    id bigint NOT NULL,
    eje_tematico_id integer NOT NULL,
    nivel_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE ejes_tematicos_niveles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ejes_tematicos_niveles IS 'Relación N:M entre ejes temáticos y niveles educativos. Define qué ejes son evaluables en cada grado.';


--
-- Name: ejes_tematicos_niveles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ejes_tematicos_niveles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ejes_tematicos_niveles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_tokens (
    id bigint NOT NULL,
    usuario_id integer NOT NULL,
    tipo character varying(30) NOT NULL,
    token_hash character varying(64) NOT NULL,
    expira_en timestamp with time zone NOT NULL,
    usado_en timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    intentos integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_email_token_tipo CHECK (((tipo)::text = ANY ((ARRAY['VERIFICACION_EMAIL'::character varying, 'RESET_PASSWORD'::character varying])::text[])))
);


--
-- Name: TABLE email_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.email_tokens IS 'Tokens de un solo uso para verificación de email y reset de contraseña. Guardados como SHA-256 del valor enviado por correo.';


--
-- Name: COLUMN email_tokens.intentos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.email_tokens.intentos IS 'Número de validaciones fallidas. Tras 5 el token se invalida automáticamente para limitar brute-force del código de reset.';


--
-- Name: email_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escalas_valoracion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escalas_valoracion (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    etiqueta character(1) NOT NULL,
    valor_numerico smallint NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_escala_valor CHECK (((valor_numerico >= 1) AND (valor_numerico <= 4)))
);


--
-- Name: TABLE escalas_valoracion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.escalas_valoracion IS 'Escala Likert 1-4: I, B, S, D.';


--
-- Name: COLUMN escalas_valoracion.valor_numerico; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.escalas_valoracion.valor_numerico IS '1=Insuficiente 2=Básico 3=Satisfactorio 4=Destacado';


--
-- Name: escalas_valoracion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escalas_valoracion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escalas_valoracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estudiantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estudiantes (
    id integer NOT NULL,
    identificacion character varying(25) NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido1 character varying(100) NOT NULL,
    apellido2 character varying(100),
    fecha_nacimiento date,
    genero character(1),
    nombre_acudiente character varying(200),
    telefono_acudiente character varying(20),
    correo_acudiente character varying(150),
    estado character varying(10) DEFAULT 'ACTIVO'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_estudiante_estado CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying, 'TRASLADADO'::character varying])::text[]))),
    CONSTRAINT estudiantes_genero_check CHECK ((genero = ANY (ARRAY['M'::bpchar, 'F'::bpchar, 'O'::bpchar])))
);


--
-- Name: TABLE estudiantes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.estudiantes IS 'Datos personales estables del estudiante (nombre, identificacion, acudiente, etc.). La asignación a secciones por año lectivo se registra en la tabla matriculas.';


--
-- Name: COLUMN estudiantes.identificacion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.estudiantes.identificacion IS 'Obligatorio y único; código institucional o cédula de identidad del estudiante.';


--
-- Name: COLUMN estudiantes.estado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.estudiantes.estado IS 'Estado global del estudiante. TRASLADADO = salió de la institución. Detalle de cada año lectivo en matriculas.';


--
-- Name: estudiantes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estudiantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estudiantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluaciones (
    id integer NOT NULL,
    estudiante_id integer NOT NULL,
    periodo_id integer NOT NULL,
    usuario_id integer NOT NULL,
    seccion_id integer NOT NULL,
    observacion_general text,
    origen_registro character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_origen_registro CHECK (((origen_registro)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTOMATICO'::character varying])::text[])))
);


--
-- Name: TABLE evaluaciones; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.evaluaciones IS 'Cabecera de evaluación: enlaza estudiante, docente y período.';


--
-- Name: COLUMN evaluaciones.seccion_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.evaluaciones.seccion_id IS 'Sección en el momento de la evaluación. Denormalizado desde matriculas para preservar el contexto histórico.';


--
-- Name: evaluaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evaluaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluaciones_saber; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluaciones_saber (
    id bigint NOT NULL,
    estudiante_id bigint NOT NULL,
    periodo_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    seccion_id bigint NOT NULL,
    tipo_saber_id integer NOT NULL,
    fecha_evaluacion date DEFAULT CURRENT_DATE NOT NULL,
    observacion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    materia_id integer NOT NULL
);


--
-- Name: TABLE evaluaciones_saber; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.evaluaciones_saber IS 'Cabecera de evaluación por tipo de saber. Permite múltiples evaluaciones por estudiante/periodo/tipo.';


--
-- Name: evaluaciones_saber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evaluaciones_saber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluaciones_saber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materias (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    clave character varying(30) NOT NULL
);


--
-- Name: TABLE materias; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.materias IS 'Áreas curriculares: Matemáticas, Español, Ciencias, Estudios Sociales.';


--
-- Name: materias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matriculas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matriculas (
    id integer NOT NULL,
    estudiante_id integer NOT NULL,
    seccion_id integer NOT NULL,
    anio_lectivo_id integer NOT NULL,
    estado character varying(10) DEFAULT 'ACTIVO'::character varying NOT NULL,
    fecha_matricula date DEFAULT CURRENT_DATE NOT NULL,
    observaciones text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_matricula_estado CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'RETIRADO'::character varying])::text[])))
);


--
-- Name: TABLE matriculas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.matriculas IS 'Historial de asignación estudiante↔sección por año lectivo. Un estudiante puede pertenecer a varias secciones en el mismo año (una por docente/materia). UNIQUE (estudiante_id, seccion_id) evita matrículas duplicadas en una misma sección.';


--
-- Name: COLUMN matriculas.anio_lectivo_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.matriculas.anio_lectivo_id IS 'Denormalizado desde secciones.anio_lectivo_id para consultar e indexar matrículas por año.';


--
-- Name: COLUMN matriculas.estado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.matriculas.estado IS 'ACTIVO = cursando normalmente. RETIRADO = abandonó la institución durante el año lectivo.';


--
-- Name: matriculas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matriculas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matriculas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: niveles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.niveles (
    id integer NOT NULL,
    numero_grado smallint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_grado_rango CHECK (((numero_grado >= 1) AND (numero_grado <= 6)))
);


--
-- Name: TABLE niveles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.niveles IS 'Catálogo fijo: grados 1° a 6° de educación primaria.';


--
-- Name: COLUMN niveles.numero_grado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.niveles.numero_grado IS '1 = Primer Grado … 6 = Sexto Grado.';


--
-- Name: niveles_desempeno; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.niveles_desempeno (
    id integer NOT NULL,
    valor_numerico smallint NOT NULL,
    nombre character varying(50) NOT NULL,
    etiqueta character varying(5) NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_ndesempeno_rango CHECK (((valor_numerico >= 1) AND (valor_numerico <= 5)))
);


--
-- Name: TABLE niveles_desempeno; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.niveles_desempeno IS 'Escala de valoración de 5 niveles para evaluaciones por saberes.';


--
-- Name: niveles_desempeno_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.niveles_desempeno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.niveles_desempeno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: niveles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.niveles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.niveles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: periodos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.periodos (
    id integer NOT NULL,
    anio_lectivo_id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    numero_periodo smallint NOT NULL,
    activo boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_periodo_numero CHECK (((numero_periodo >= 1) AND (numero_periodo <= 6)))
);


--
-- Name: TABLE periodos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.periodos IS 'Períodos trimestral o cuatrimestre de evaluación dentro de un año lectivo.';


--
-- Name: COLUMN periodos.activo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.periodos.activo IS 'TRUE = período de evaluación en curso. Índice parcial garantiza unicidad por año.';


--
-- Name: periodos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.periodos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.periodos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registro_auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registro_auditoria (
    id integer NOT NULL,
    usuario_id integer,
    accion character varying(50) NOT NULL,
    tabla_nombre character varying(100),
    registro_id bigint,
    valores_anteriores jsonb,
    valores_nuevos jsonb,
    ip_origen inet,
    user_agent character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE registro_auditoria; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.registro_auditoria IS 'Log inmutable de acciones de usuario para seguridad y cumplimiento.';


--
-- Name: COLUMN registro_auditoria.registro_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.registro_auditoria.registro_id IS 'BIGINT para soportar PKs de cualquier tipo sin migración futura.';


--
-- Name: registro_auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registro_auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registro_auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE roles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.roles IS 'Catálogo de roles del sistema: ADMIN, DOCENTE, COORDINADOR.';


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.secciones (
    id integer NOT NULL,
    nombre character varying(10) NOT NULL,
    nivel_id integer NOT NULL,
    centro_id integer NOT NULL,
    anio_lectivo_id integer NOT NULL,
    docente_id integer,
    capacidad smallint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT secciones_capacidad_check CHECK ((capacidad > 0))
);


--
-- Name: TABLE secciones; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.secciones IS 'Grupo-aula: combinación única de nivel, centro, año lectivo y letra.';


--
-- Name: COLUMN secciones.docente_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.secciones.docente_id IS 'Docente titular. Otros docentes asignados via usuarios_secciones esta opcion es opcional .';


--
-- Name: secciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.secciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_saber; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_saber (
    id integer NOT NULL,
    clave character varying(20) NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE tipos_saber; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tipos_saber IS 'Catálogo de tipos de saber: Conceptual, Procedimental, Actitudinal.';


--
-- Name: tipos_saber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_saber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_saber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tokens_refresh; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tokens_refresh (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    token_hash character varying(255) NOT NULL,
    expira_en timestamp with time zone NOT NULL,
    revocado boolean DEFAULT false NOT NULL,
    revocado_en timestamp with time zone,
    ip_origen inet,
    user_agent character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_token_revocacion CHECK ((((revocado = false) AND (revocado_en IS NULL)) OR ((revocado = true) AND (revocado_en IS NOT NULL))))
);


--
-- Name: TABLE tokens_refresh; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tokens_refresh IS 'Tokens de refresco JWT. Almacena hash SHA-256 para poder invalidarlos.';


--
-- Name: COLUMN tokens_refresh.token_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tokens_refresh.token_hash IS 'SHA-256 del refresh token. Nunca almacenar el token en claro.';


--
-- Name: tokens_refresh_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tokens_refresh ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_refresh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_materias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_materias (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    materia_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: usuario_materias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuario_materias_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuario_materias_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuario_materias_id_seq OWNED BY public.usuario_materias.id;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    apellidos character varying(150) NOT NULL,
    correo character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    rol_id integer NOT NULL,
    estado character varying(10) DEFAULT 'ACTIVO'::character varying NOT NULL,
    ultimo_acceso timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    email_verificado boolean DEFAULT false NOT NULL,
    debe_cambiar_password boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_usuario_estado CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);


--
-- Name: TABLE usuarios; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.usuarios IS 'Usuarios del sistema: ADMIN, DOCENTE y COORDINADOR.';


--
-- Name: COLUMN usuarios.password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.password IS 'Hash BCrypt (exactamente 60 caracteres). Ver ACCIÓN REQUERIDA en README.';


--
-- Name: COLUMN usuarios.debe_cambiar_password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.debe_cambiar_password IS 'TRUE cuando el usuario tiene una contraseña temporal asignada por el admin y debe cambiarla en su primer acceso.';


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_secciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_secciones (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    seccion_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE usuarios_secciones; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.usuarios_secciones IS 'Docentes (o coordinadores) asignados a una o más secciones. Es diferente a la tabla secciones ya que es mas como para agregar a mas profesores relacionadas a la seccion .';


--
-- Name: usuarios_secciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_secciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_secciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vw_alertas_activas; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_alertas_activas AS
 SELECT a.id AS alerta_id,
    a.tipo_alerta,
    a.nivel_alerta,
    a.fecha_generacion,
    a.motivo,
    e.id AS estudiante_id,
    (((e.nombre)::text || ' '::text) || (e.apellido1)::text) AS nombre_estudiante,
    ce.nombre AS centro,
    n.nombre AS nivel,
    sec.nombre AS seccion,
    m.nombre AS materia,
    c.nombre AS contenido_afectado,
    (((u.nombre)::text || ' '::text) || (u.apellidos)::text) AS generada_por,
    p.nombre AS periodo
   FROM (((((((((public.alertas a
     JOIN public.estudiantes e ON ((e.id = a.estudiante_id)))
     JOIN public.periodos p ON ((p.id = a.periodo_id)))
     JOIN public.matriculas mat ON (((mat.estudiante_id = e.id) AND (mat.anio_lectivo_id = p.anio_lectivo_id))))
     JOIN public.secciones sec ON ((sec.id = mat.seccion_id)))
     JOIN public.niveles n ON ((n.id = sec.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = sec.centro_id)))
     JOIN public.contenidos c ON ((c.id = a.contenido_id)))
     JOIN public.materias m ON ((m.id = c.materia_id)))
     LEFT JOIN public.usuarios u ON ((u.id = a.generada_por)))
  WHERE ((a.estado)::text = 'ACTIVA'::text)
  ORDER BY
        CASE a.nivel_alerta
            WHEN 'ALTO'::text THEN 1
            WHEN 'MEDIO'::text THEN 2
            WHEN 'BAJO'::text THEN 3
            ELSE NULL::integer
        END, a.fecha_generacion DESC;


--
-- Name: VIEW vw_alertas_activas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_alertas_activas IS 'Alertas en estado ACTIVA ordenadas por severidad y fecha. Usa INNER JOIN con matriculas: alertas sin matrícula registrada para ese año lectivo no aparecen en esta vista. Usar vw_historial_por_dimension para consultas históricas.';


--
-- Name: vw_criterios_completos; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_criterios_completos AS
 SELECT ci.id AS criterio_id,
    ci.nombre AS criterio,
    ci.descripcion AS criterio_descripcion,
    ci.peso AS criterio_peso,
    c.id AS contenido_id,
    c.nombre AS contenido,
    m.id AS materia_id,
    m.nombre AS materia,
    d.id AS dimension_id,
    d.nombre AS dimension,
    d.peso AS dimension_peso
   FROM (((public.criterios_indicadores ci
     JOIN public.contenidos c ON ((c.id = ci.contenido_id)))
     JOIN public.materias m ON ((m.id = c.materia_id)))
     JOIN public.dimensiones_evaluacion d ON ((d.id = ci.dimension_id)));


--
-- Name: VIEW vw_criterios_completos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_criterios_completos IS 'Jerarquía completa: criterio → contenido → materia → dimensión.';


--
-- Name: vw_docentes_por_seccion; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_docentes_por_seccion AS
 SELECT u.id AS usuario_id,
    (((u.nombre)::text || ' '::text) || (u.apellidos)::text) AS docente,
    u.correo,
    s.id AS seccion_id,
    s.nombre AS seccion,
    n.nombre AS nivel,
    ce.nombre AS centro,
    al.anio AS anio_lectivo
   FROM (((((public.usuarios_secciones us
     JOIN public.usuarios u ON ((u.id = us.usuario_id)))
     JOIN public.secciones s ON ((s.id = us.seccion_id)))
     JOIN public.niveles n ON ((n.id = s.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = s.centro_id)))
     JOIN public.anios_lectivos al ON ((al.id = s.anio_lectivo_id)))
  WHERE (((u.estado)::text = 'ACTIVO'::text) AND (al.activo = true));


--
-- Name: VIEW vw_docentes_por_seccion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_docentes_por_seccion IS 'Asignaciones docente-sección del año lectivo activo.';


--
-- Name: vw_ejes_por_materia_nivel; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_ejes_por_materia_nivel AS
 SELECT en.nivel_id,
    n.numero_grado,
    e.materia_id,
    m.clave AS materia_clave,
    m.nombre AS materia_nombre,
    e.tipo_saber_id,
    ts.clave AS tipo_saber_clave,
    ts.nombre AS tipo_saber_nombre,
    e.id AS eje_id,
    e.clave AS eje_clave,
    e.nombre AS eje_nombre,
    e.descripcion AS eje_descripcion,
    e.orden AS eje_orden,
    e.periodo_numero AS eje_periodo
   FROM ((((public.ejes_tematicos_niveles en
     JOIN public.ejes_tematicos e ON ((e.id = en.eje_tematico_id)))
     JOIN public.niveles n ON ((n.id = en.nivel_id)))
     JOIN public.materias m ON ((m.id = e.materia_id)))
     JOIN public.tipos_saber ts ON ((ts.id = e.tipo_saber_id)));


--
-- Name: VIEW vw_ejes_por_materia_nivel; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_ejes_por_materia_nivel IS 'Catálogo plano de ejes filtrables por materia, tipo de saber, nivel/grado y trimestre.';


--
-- Name: vw_rendimiento_periodo_activo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_rendimiento_periodo_activo AS
 SELECT e.id AS estudiante_id,
    (((e.nombre)::text || ' '::text) || (e.apellido1)::text) AS nombre_completo,
    n.nombre AS nivel,
    sec.nombre AS seccion,
    ce.nombre AS centro,
    p.nombre AS periodo,
    round(avg(esc.valor_numerico), 2) AS promedio_general,
    count(de.id) AS criterios_evaluados
   FROM (((((((public.estudiantes e
     JOIN public.evaluaciones ev ON ((ev.estudiante_id = e.id)))
     JOIN public.secciones sec ON ((sec.id = ev.seccion_id)))
     JOIN public.niveles n ON ((n.id = sec.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = sec.centro_id)))
     JOIN public.periodos p ON ((p.id = ev.periodo_id)))
     JOIN public.detalle_evaluacion de ON ((de.evaluacion_id = ev.id)))
     JOIN public.escalas_valoracion esc ON ((esc.id = de.escala_id)))
  WHERE ((p.activo = true) AND ((e.estado)::text = 'ACTIVO'::text))
  GROUP BY e.id, e.nombre, e.apellido1, n.nombre, sec.nombre, ce.nombre, p.nombre;


--
-- Name: VIEW vw_rendimiento_periodo_activo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_rendimiento_periodo_activo IS 'Promedio Likert por estudiante en el período activo. Ordenar ASC para ver mayor riesgo primero.';


--
-- Name: vw_estudiantes_en_riesgo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_estudiantes_en_riesgo AS
 SELECT estudiante_id,
    nombre_completo,
    nivel,
    seccion,
    centro,
    periodo,
    promedio_general,
    criterios_evaluados,
        CASE
            WHEN (promedio_general < 1.5) THEN 'CRITICA'::text
            WHEN (promedio_general < 2.0) THEN 'MODERADA'::text
            ELSE 'PREVENTIVA'::text
        END AS tipo_alerta_sugerida,
        CASE
            WHEN (promedio_general < 1.5) THEN 'ALTO'::text
            WHEN (promedio_general < 2.0) THEN 'MEDIO'::text
            ELSE 'BAJO'::text
        END AS nivel_riesgo_sugerido
   FROM public.vw_rendimiento_periodo_activo
  WHERE (promedio_general < 2.5)
  ORDER BY promedio_general;


--
-- Name: VIEW vw_estudiantes_en_riesgo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_estudiantes_en_riesgo IS 'Estudiantes con promedio < 2.5 en el período activo. Ordenados por promedio ASC (el más bajo = mayor riesgo primero).';


--
-- Name: vw_evaluaciones_periodo_activo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_evaluaciones_periodo_activo AS
 SELECT ev.id AS evaluacion_id,
    ev.estudiante_id,
    (((e.nombre)::text || ' '::text) || (e.apellido1)::text) AS nombre_estudiante,
    ev.usuario_id,
    (((u.nombre)::text || ' '::text) || (u.apellidos)::text) AS docente,
    ev.seccion_id,
    sec.nombre AS seccion,
    n.nombre AS nivel,
    ce.nombre AS centro,
    p.id AS periodo_id,
    p.nombre AS periodo,
    ev.observacion_general,
    ev.origen_registro,
    ev.created_at
   FROM ((((((public.evaluaciones ev
     JOIN public.estudiantes e ON ((e.id = ev.estudiante_id)))
     JOIN public.usuarios u ON ((u.id = ev.usuario_id)))
     JOIN public.secciones sec ON ((sec.id = ev.seccion_id)))
     JOIN public.niveles n ON ((n.id = sec.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = sec.centro_id)))
     JOIN public.periodos p ON ((p.id = ev.periodo_id)))
  WHERE ((p.activo = true) AND ((e.estado)::text = 'ACTIVO'::text));


--
-- Name: VIEW vw_evaluaciones_periodo_activo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_evaluaciones_periodo_activo IS 'Cabeceras de evaluación del período activo con contexto completo.';


--
-- Name: vw_historial_por_dimension; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_historial_por_dimension AS
 SELECT ev.estudiante_id,
    (((e.nombre)::text || ' '::text) || (e.apellido1)::text) AS nombre_completo,
    p.numero_periodo,
    p.nombre AS periodo,
    al.anio AS anio_lectivo,
    d.nombre AS dimension,
    d.peso AS dimension_peso,
    round(avg(esc.valor_numerico), 2) AS promedio_dimension
   FROM (((((((public.evaluaciones ev
     JOIN public.periodos p ON ((p.id = ev.periodo_id)))
     JOIN public.anios_lectivos al ON ((al.id = p.anio_lectivo_id)))
     JOIN public.detalle_evaluacion de ON ((de.evaluacion_id = ev.id)))
     JOIN public.criterios_indicadores ci ON ((ci.id = de.criterio_id)))
     JOIN public.dimensiones_evaluacion d ON ((d.id = ci.dimension_id)))
     JOIN public.escalas_valoracion esc ON ((esc.id = de.escala_id)))
     JOIN public.estudiantes e ON ((e.id = ev.estudiante_id)))
  WHERE ((e.estado)::text = 'ACTIVO'::text)
  GROUP BY ev.estudiante_id, e.nombre, e.apellido1, p.numero_periodo, p.nombre, al.anio, d.id, d.nombre, d.peso
  ORDER BY ev.estudiante_id, al.anio, p.numero_periodo, d.nombre;


--
-- Name: VIEW vw_historial_por_dimension; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_historial_por_dimension IS 'Promedio por dimensión en cada período histórico. Filtrar por estudiante_id en el backend.';


--
-- Name: vw_matriculas_anio_activo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_matriculas_anio_activo AS
 SELECT e.id AS estudiante_id,
    e.identificacion,
    (((e.nombre)::text || ' '::text) || (e.apellido1)::text) AS nombre_completo,
    e.apellido2,
    e.genero,
    e.estado AS estado_estudiante,
    mat.id AS matricula_id,
    mat.estado AS estado_matricula,
    mat.fecha_matricula,
    s.id AS seccion_id,
    s.nombre AS seccion,
    n.numero_grado,
    n.nombre AS nivel,
    ce.id AS centro_id,
    ce.nombre AS centro,
    al.anio AS anio_lectivo
   FROM (((((public.matriculas mat
     JOIN public.estudiantes e ON ((e.id = mat.estudiante_id)))
     JOIN public.secciones s ON ((s.id = mat.seccion_id)))
     JOIN public.niveles n ON ((n.id = s.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = s.centro_id)))
     JOIN public.anios_lectivos al ON ((al.id = mat.anio_lectivo_id)))
  WHERE ((al.activo = true) AND ((mat.estado)::text = 'ACTIVO'::text) AND ((e.estado)::text = 'ACTIVO'::text));


--
-- Name: VIEW vw_matriculas_anio_activo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_matriculas_anio_activo IS 'Estudiantes activos con su sección asignada en el año lectivo activo. Fuente canónica para consultas de sección actual.';


--
-- Name: vw_promedios_ejes_periodo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_promedios_ejes_periodo AS
 SELECT es.estudiante_id,
    es.periodo_id,
    es.materia_id,
    m.nombre AS materia_nombre,
    det.eje_tematico_id,
    ej.nombre AS eje_nombre,
    ej.tipo_saber_id,
    ts.nombre AS tipo_saber_nombre,
    count(det.id) AS total_evaluaciones,
    round(avg(det.valor), 2) AS promedio,
    min(det.valor) AS valor_minimo,
    max(det.valor) AS valor_maximo
   FROM ((((public.detalle_evaluacion_saber det
     JOIN public.evaluaciones_saber es ON ((es.id = det.evaluacion_saber_id)))
     JOIN public.ejes_tematicos ej ON ((ej.id = det.eje_tematico_id)))
     JOIN public.tipos_saber ts ON ((ts.id = ej.tipo_saber_id)))
     JOIN public.materias m ON ((m.id = es.materia_id)))
  GROUP BY es.estudiante_id, es.periodo_id, es.materia_id, m.nombre, det.eje_tematico_id, ej.nombre, ej.tipo_saber_id, ts.nombre;


--
-- Name: vw_secciones_activas; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vw_secciones_activas AS
 SELECT s.id AS seccion_id,
    s.nombre AS seccion,
    n.numero_grado,
    n.nombre AS nivel,
    ce.id AS centro_id,
    ce.nombre AS centro,
    ce.circuito,
    al.anio AS anio_lectivo,
    s.capacidad,
    s.docente_id
   FROM (((public.secciones s
     JOIN public.niveles n ON ((n.id = s.nivel_id)))
     JOIN public.centros_educativos ce ON ((ce.id = s.centro_id)))
     JOIN public.anios_lectivos al ON ((al.id = s.anio_lectivo_id)))
  WHERE (al.activo = true);


--
-- Name: VIEW vw_secciones_activas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON VIEW public.vw_secciones_activas IS 'Secciones del año lectivo activo con contexto de nivel y centro.';


--
-- Name: usuario_materias id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_materias ALTER COLUMN id SET DEFAULT nextval('public.usuario_materias_id_seq'::regclass);


--
-- Name: alertas alertas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_pkey PRIMARY KEY (id);


--
-- Name: alertas_tematicas alertas_tematicas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_pkey PRIMARY KEY (id);


--
-- Name: anios_lectivos anios_lectivos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anios_lectivos
    ADD CONSTRAINT anios_lectivos_pkey PRIMARY KEY (id);


--
-- Name: centros_educativos centros_educativos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.centros_educativos
    ADD CONSTRAINT centros_educativos_pkey PRIMARY KEY (id);


--
-- Name: configuracion_alertas configuracion_alertas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_alertas
    ADD CONSTRAINT configuracion_alertas_pkey PRIMARY KEY (id);


--
-- Name: contenidos contenidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contenidos
    ADD CONSTRAINT contenidos_pkey PRIMARY KEY (id);


--
-- Name: criterios_indicadores criterios_indicadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.criterios_indicadores
    ADD CONSTRAINT criterios_indicadores_pkey PRIMARY KEY (id);


--
-- Name: detalle_evaluacion detalle_evaluacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion
    ADD CONSTRAINT detalle_evaluacion_pkey PRIMARY KEY (id);


--
-- Name: detalle_evaluacion_saber detalle_evaluacion_saber_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion_saber
    ADD CONSTRAINT detalle_evaluacion_saber_pkey PRIMARY KEY (id);


--
-- Name: dimensiones_evaluacion dimensiones_evaluacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dimensiones_evaluacion
    ADD CONSTRAINT dimensiones_evaluacion_pkey PRIMARY KEY (id);


--
-- Name: ejes_tematicos_niveles ejes_tematicos_niveles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos_niveles
    ADD CONSTRAINT ejes_tematicos_niveles_pkey PRIMARY KEY (id);


--
-- Name: ejes_tematicos ejes_tematicos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos
    ADD CONSTRAINT ejes_tematicos_pkey PRIMARY KEY (id);


--
-- Name: email_tokens email_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT email_tokens_pkey PRIMARY KEY (id);


--
-- Name: escalas_valoracion escalas_valoracion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalas_valoracion
    ADD CONSTRAINT escalas_valoracion_pkey PRIMARY KEY (id);


--
-- Name: estudiantes estudiantes_identificacion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiantes
    ADD CONSTRAINT estudiantes_identificacion_key UNIQUE (identificacion);


--
-- Name: estudiantes estudiantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estudiantes
    ADD CONSTRAINT estudiantes_pkey PRIMARY KEY (id);


--
-- Name: evaluaciones evaluaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT evaluaciones_pkey PRIMARY KEY (id);


--
-- Name: evaluaciones_saber evaluaciones_saber_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_pkey PRIMARY KEY (id);


--
-- Name: materias materias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT materias_pkey PRIMARY KEY (id);


--
-- Name: matriculas matriculas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matriculas
    ADD CONSTRAINT matriculas_pkey PRIMARY KEY (id);


--
-- Name: niveles_desempeno niveles_desempeno_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles_desempeno
    ADD CONSTRAINT niveles_desempeno_pkey PRIMARY KEY (id);


--
-- Name: niveles niveles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles
    ADD CONSTRAINT niveles_pkey PRIMARY KEY (id);


--
-- Name: periodos periodos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periodos
    ADD CONSTRAINT periodos_pkey PRIMARY KEY (id);


--
-- Name: registro_auditoria registro_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro_auditoria
    ADD CONSTRAINT registro_auditoria_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: secciones secciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT secciones_pkey PRIMARY KEY (id);


--
-- Name: tipos_saber tipos_saber_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_saber
    ADD CONSTRAINT tipos_saber_pkey PRIMARY KEY (id);


--
-- Name: tokens_refresh tokens_refresh_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_refresh
    ADD CONSTRAINT tokens_refresh_pkey PRIMARY KEY (id);


--
-- Name: tokens_refresh tokens_refresh_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_refresh
    ADD CONSTRAINT tokens_refresh_token_hash_key UNIQUE (token_hash);


--
-- Name: alertas_tematicas uq_alerta_tematica; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT uq_alerta_tematica UNIQUE (estudiante_id, periodo_id, eje_tematico_id, materia_id, seccion_id, nivel_alerta);


--
-- Name: anios_lectivos uq_anio_lectivo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anios_lectivos
    ADD CONSTRAINT uq_anio_lectivo UNIQUE (anio);


--
-- Name: centros_educativos uq_centro_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.centros_educativos
    ADD CONSTRAINT uq_centro_nombre UNIQUE (nombre);


--
-- Name: contenidos uq_contenido_por_materia; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contenidos
    ADD CONSTRAINT uq_contenido_por_materia UNIQUE (materia_id, nombre);


--
-- Name: criterios_indicadores uq_criterio_por_contenido; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.criterios_indicadores
    ADD CONSTRAINT uq_criterio_por_contenido UNIQUE (contenido_id, nombre);


--
-- Name: detalle_evaluacion uq_detalle_criterio; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion
    ADD CONSTRAINT uq_detalle_criterio UNIQUE (evaluacion_id, criterio_id);


--
-- Name: detalle_evaluacion_saber uq_detalle_saber_eje; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion_saber
    ADD CONSTRAINT uq_detalle_saber_eje UNIQUE (evaluacion_saber_id, eje_tematico_id);


--
-- Name: dimensiones_evaluacion uq_dimension_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dimensiones_evaluacion
    ADD CONSTRAINT uq_dimension_nombre UNIQUE (nombre);


--
-- Name: ejes_tematicos uq_eje_clave; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos
    ADD CONSTRAINT uq_eje_clave UNIQUE (clave);


--
-- Name: ejes_tematicos_niveles uq_eje_nivel; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos_niveles
    ADD CONSTRAINT uq_eje_nivel UNIQUE (eje_tematico_id, nivel_id);


--
-- Name: ejes_tematicos uq_eje_por_materia_tipo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos
    ADD CONSTRAINT uq_eje_por_materia_tipo UNIQUE (materia_id, tipo_saber_id, orden);


--
-- Name: email_tokens uq_email_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT uq_email_token_hash UNIQUE (token_hash);


--
-- Name: escalas_valoracion uq_escala_etiqueta; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalas_valoracion
    ADD CONSTRAINT uq_escala_etiqueta UNIQUE (etiqueta);


--
-- Name: escalas_valoracion uq_escala_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalas_valoracion
    ADD CONSTRAINT uq_escala_nombre UNIQUE (nombre);


--
-- Name: escalas_valoracion uq_escala_valor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escalas_valoracion
    ADD CONSTRAINT uq_escala_valor UNIQUE (valor_numerico);


--
-- Name: matriculas uq_estudiante_por_seccion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matriculas
    ADD CONSTRAINT uq_estudiante_por_seccion UNIQUE (estudiante_id, seccion_id);


--
-- Name: evaluaciones uq_evaluacion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT uq_evaluacion UNIQUE (estudiante_id, usuario_id, periodo_id);


--
-- Name: materias uq_materia_clave; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT uq_materia_clave UNIQUE (clave);


--
-- Name: materias uq_materia_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT uq_materia_nombre UNIQUE (nombre);


--
-- Name: niveles_desempeno uq_ndesempeno_etiqueta; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles_desempeno
    ADD CONSTRAINT uq_ndesempeno_etiqueta UNIQUE (etiqueta);


--
-- Name: niveles_desempeno uq_ndesempeno_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles_desempeno
    ADD CONSTRAINT uq_ndesempeno_nombre UNIQUE (nombre);


--
-- Name: niveles_desempeno uq_ndesempeno_valor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles_desempeno
    ADD CONSTRAINT uq_ndesempeno_valor UNIQUE (valor_numerico);


--
-- Name: niveles uq_nivel_grado; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles
    ADD CONSTRAINT uq_nivel_grado UNIQUE (numero_grado);


--
-- Name: niveles uq_nivel_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles
    ADD CONSTRAINT uq_nivel_nombre UNIQUE (nombre);


--
-- Name: periodos uq_periodo_por_anio; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periodos
    ADD CONSTRAINT uq_periodo_por_anio UNIQUE (anio_lectivo_id, numero_periodo);


--
-- Name: roles uq_rol_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uq_rol_nombre UNIQUE (nombre);


--
-- Name: secciones uq_seccion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT uq_seccion UNIQUE (nivel_id, centro_id, anio_lectivo_id, nombre);


--
-- Name: tipos_saber uq_tipo_saber_clave; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_saber
    ADD CONSTRAINT uq_tipo_saber_clave UNIQUE (clave);


--
-- Name: tipos_saber uq_tipo_saber_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_saber
    ADD CONSTRAINT uq_tipo_saber_nombre UNIQUE (nombre);


--
-- Name: usuarios uq_usuario_correo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uq_usuario_correo UNIQUE (correo);


--
-- Name: usuario_materias uq_usuario_materia; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_materias
    ADD CONSTRAINT uq_usuario_materia UNIQUE (usuario_id, materia_id);


--
-- Name: usuarios_secciones uq_usuario_seccion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_secciones
    ADD CONSTRAINT uq_usuario_seccion UNIQUE (usuario_id, seccion_id);


--
-- Name: usuario_materias usuario_materias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_materias
    ADD CONSTRAINT usuario_materias_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios_secciones usuarios_secciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_secciones
    ADD CONSTRAINT usuarios_secciones_pkey PRIMARY KEY (id);


--
-- Name: idx_alerta_tem_eje; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_eje ON public.alertas_tematicas USING btree (eje_tematico_id);


--
-- Name: idx_alerta_tem_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_estado ON public.alertas_tematicas USING btree (estado);


--
-- Name: idx_alerta_tem_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_estudiante ON public.alertas_tematicas USING btree (estudiante_id);


--
-- Name: idx_alerta_tem_materia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_materia ON public.alertas_tematicas USING btree (materia_id);


--
-- Name: idx_alerta_tem_nivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_nivel ON public.alertas_tematicas USING btree (nivel_alerta);


--
-- Name: idx_alerta_tem_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_periodo ON public.alertas_tematicas USING btree (periodo_id);


--
-- Name: idx_alerta_tem_seccion_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alerta_tem_seccion_periodo ON public.alertas_tematicas USING btree (seccion_id, periodo_id);


--
-- Name: idx_alertas_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alertas_estado ON public.alertas USING btree (estado);


--
-- Name: idx_alertas_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alertas_estudiante ON public.alertas USING btree (estudiante_id);


--
-- Name: idx_alertas_evaluacion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alertas_evaluacion ON public.alertas USING btree (evaluacion_id);


--
-- Name: idx_alertas_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alertas_fecha ON public.alertas USING btree (fecha_generacion DESC);


--
-- Name: idx_alertas_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alertas_periodo ON public.alertas USING btree (periodo_id);


--
-- Name: idx_anios_activo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_anios_activo ON public.anios_lectivos USING btree (activo);


--
-- Name: idx_audit_accion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_accion ON public.registro_auditoria USING btree (accion);


--
-- Name: idx_audit_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_fecha ON public.registro_auditoria USING btree (created_at DESC);


--
-- Name: idx_audit_tabla; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_tabla ON public.registro_auditoria USING btree (tabla_nombre);


--
-- Name: idx_audit_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_usuario ON public.registro_auditoria USING btree (usuario_id);


--
-- Name: idx_config_alerta_dimension; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_config_alerta_dimension ON public.configuracion_alertas USING btree (dimension_id);


--
-- Name: idx_contenidos_materia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contenidos_materia ON public.contenidos USING btree (materia_id);


--
-- Name: idx_criterios_contenido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_criterios_contenido ON public.criterios_indicadores USING btree (contenido_id);


--
-- Name: idx_criterios_dimension; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_criterios_dimension ON public.criterios_indicadores USING btree (dimension_id);


--
-- Name: idx_det_saber_eje; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_det_saber_eje ON public.detalle_evaluacion_saber USING btree (eje_tematico_id);


--
-- Name: idx_det_saber_evaluacion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_det_saber_evaluacion ON public.detalle_evaluacion_saber USING btree (evaluacion_saber_id);


--
-- Name: idx_detalle_criterio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_detalle_criterio ON public.detalle_evaluacion USING btree (criterio_id);


--
-- Name: idx_detalle_escala; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_detalle_escala ON public.detalle_evaluacion USING btree (escala_id);


--
-- Name: idx_detalle_evaluacion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_detalle_evaluacion ON public.detalle_evaluacion USING btree (evaluacion_id);


--
-- Name: idx_eje_nivel_eje; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eje_nivel_eje ON public.ejes_tematicos_niveles USING btree (eje_tematico_id);


--
-- Name: idx_eje_nivel_nivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eje_nivel_nivel ON public.ejes_tematicos_niveles USING btree (nivel_id);


--
-- Name: idx_ejes_materia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ejes_materia ON public.ejes_tematicos USING btree (materia_id);


--
-- Name: idx_ejes_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ejes_periodo ON public.ejes_tematicos USING btree (periodo_numero);


--
-- Name: idx_ejes_tipo_saber; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ejes_tipo_saber ON public.ejes_tematicos USING btree (tipo_saber_id);


--
-- Name: idx_email_tokens_pendientes; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_tokens_pendientes ON public.email_tokens USING btree (expira_en) WHERE (usado_en IS NULL);


--
-- Name: idx_email_tokens_tipo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_tokens_tipo ON public.email_tokens USING btree (tipo);


--
-- Name: idx_email_tokens_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_tokens_usuario ON public.email_tokens USING btree (usuario_id);


--
-- Name: idx_estudiantes_apellido1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_estudiantes_apellido1 ON public.estudiantes USING btree (apellido1, nombre);


--
-- Name: idx_estudiantes_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_estudiantes_estado ON public.estudiantes USING btree (estado);


--
-- Name: idx_eval_est_per; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_est_per ON public.evaluaciones USING btree (estudiante_id, periodo_id);


--
-- Name: idx_eval_saber_est_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_est_periodo ON public.evaluaciones_saber USING btree (estudiante_id, periodo_id);


--
-- Name: idx_eval_saber_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_estudiante ON public.evaluaciones_saber USING btree (estudiante_id);


--
-- Name: idx_eval_saber_materia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_materia ON public.evaluaciones_saber USING btree (materia_id);


--
-- Name: idx_eval_saber_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_periodo ON public.evaluaciones_saber USING btree (periodo_id);


--
-- Name: idx_eval_saber_seccion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_seccion ON public.evaluaciones_saber USING btree (seccion_id);


--
-- Name: idx_eval_saber_tipo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_saber_tipo ON public.evaluaciones_saber USING btree (tipo_saber_id);


--
-- Name: idx_eval_seccion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_seccion ON public.evaluaciones USING btree (seccion_id);


--
-- Name: idx_eval_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_eval_usuario ON public.evaluaciones USING btree (usuario_id);


--
-- Name: idx_matriculas_anio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matriculas_anio ON public.matriculas USING btree (anio_lectivo_id);


--
-- Name: idx_matriculas_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matriculas_estado ON public.matriculas USING btree (estado);


--
-- Name: idx_matriculas_estudiante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matriculas_estudiante ON public.matriculas USING btree (estudiante_id);


--
-- Name: idx_matriculas_seccion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_matriculas_seccion ON public.matriculas USING btree (seccion_id);


--
-- Name: idx_periodos_activo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periodos_activo ON public.periodos USING btree (activo);


--
-- Name: idx_periodos_anio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periodos_anio ON public.periodos USING btree (anio_lectivo_id);


--
-- Name: idx_secciones_anio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_secciones_anio ON public.secciones USING btree (anio_lectivo_id);


--
-- Name: idx_secciones_centro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_secciones_centro ON public.secciones USING btree (centro_id);


--
-- Name: idx_secciones_docente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_secciones_docente ON public.secciones USING btree (docente_id);


--
-- Name: idx_secciones_nivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_secciones_nivel ON public.secciones USING btree (nivel_id);


--
-- Name: idx_token_expira; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_token_expira ON public.tokens_refresh USING btree (expira_en);


--
-- Name: idx_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_token_hash ON public.tokens_refresh USING btree (token_hash);


--
-- Name: idx_token_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_token_usuario ON public.tokens_refresh USING btree (usuario_id);


--
-- Name: idx_token_vigentes; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_token_vigentes ON public.tokens_refresh USING btree (usuario_id, expira_en) WHERE (revocado = false);


--
-- Name: idx_um_materia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_um_materia ON public.usuario_materias USING btree (materia_id);


--
-- Name: idx_um_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_um_usuario ON public.usuario_materias USING btree (usuario_id);


--
-- Name: idx_us_seccion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_us_seccion ON public.usuarios_secciones USING btree (seccion_id);


--
-- Name: idx_us_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_us_usuario ON public.usuarios_secciones USING btree (usuario_id);


--
-- Name: idx_usuarios_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_estado ON public.usuarios USING btree (estado);


--
-- Name: idx_usuarios_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_rol ON public.usuarios USING btree (rol_id);


--
-- Name: uq_periodo_activo_por_anio; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_periodo_activo_por_anio ON public.periodos USING btree (anio_lectivo_id) WHERE (activo = true);


--
-- Name: uq_un_anio_activo; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_un_anio_activo ON public.anios_lectivos USING btree (activo) WHERE (activo = true);


--
-- Name: alertas_tematicas trg_alerta_tem_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_alerta_tem_updated_at BEFORE UPDATE ON public.alertas_tematicas FOR EACH ROW EXECUTE FUNCTION public.fn_eval_saber_updated_at();


--
-- Name: alertas trg_alertas_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_alertas_upd BEFORE UPDATE ON public.alertas FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: anios_lectivos trg_anios_lectivos_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_anios_lectivos_upd BEFORE UPDATE ON public.anios_lectivos FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: centros_educativos trg_centros_educativos_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_centros_educativos_upd BEFORE UPDATE ON public.centros_educativos FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: configuracion_alertas trg_config_alertas_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_config_alertas_upd BEFORE UPDATE ON public.configuracion_alertas FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: contenidos trg_contenidos_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_contenidos_upd BEFORE UPDATE ON public.contenidos FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: criterios_indicadores trg_criterios_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_criterios_upd BEFORE UPDATE ON public.criterios_indicadores FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: dimensiones_evaluacion trg_dimensiones_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_dimensiones_upd BEFORE UPDATE ON public.dimensiones_evaluacion FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: estudiantes trg_estudiantes_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_estudiantes_upd BEFORE UPDATE ON public.estudiantes FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: evaluaciones_saber trg_eval_saber_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_eval_saber_updated_at BEFORE UPDATE ON public.evaluaciones_saber FOR EACH ROW EXECUTE FUNCTION public.fn_eval_saber_updated_at();


--
-- Name: evaluaciones trg_evaluaciones_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_evaluaciones_upd BEFORE UPDATE ON public.evaluaciones FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: materias trg_materias_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_materias_upd BEFORE UPDATE ON public.materias FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: matriculas trg_matriculas_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_matriculas_upd BEFORE UPDATE ON public.matriculas FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: periodos trg_periodos_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_periodos_upd BEFORE UPDATE ON public.periodos FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: secciones trg_secciones_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_secciones_upd BEFORE UPDATE ON public.secciones FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: usuarios trg_usuarios_upd; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_usuarios_upd BEFORE UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_updated_at();


--
-- Name: alertas alertas_config_alerta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_config_alerta_id_fkey FOREIGN KEY (config_alerta_id) REFERENCES public.configuracion_alertas(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: alertas alertas_contenido_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_contenido_id_fkey FOREIGN KEY (contenido_id) REFERENCES public.contenidos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: alertas alertas_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: alertas alertas_evaluacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_evaluacion_id_fkey FOREIGN KEY (evaluacion_id) REFERENCES public.evaluaciones(id) ON DELETE SET NULL DEFERRABLE;


--
-- Name: alertas alertas_generada_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_generada_por_fkey FOREIGN KEY (generada_por) REFERENCES public.usuarios(id) ON DELETE SET NULL DEFERRABLE;


--
-- Name: alertas alertas_periodo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_periodo_id_fkey FOREIGN KEY (periodo_id) REFERENCES public.periodos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: alertas_tematicas alertas_tematicas_eje_tematico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_eje_tematico_id_fkey FOREIGN KEY (eje_tematico_id) REFERENCES public.ejes_tematicos(id) ON DELETE RESTRICT;


--
-- Name: alertas_tematicas alertas_tematicas_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id) ON DELETE RESTRICT;


--
-- Name: alertas_tematicas alertas_tematicas_generada_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_generada_por_fkey FOREIGN KEY (generada_por) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- Name: alertas_tematicas alertas_tematicas_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id) ON DELETE RESTRICT;


--
-- Name: alertas_tematicas alertas_tematicas_periodo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_periodo_id_fkey FOREIGN KEY (periodo_id) REFERENCES public.periodos(id) ON DELETE RESTRICT;


--
-- Name: alertas_tematicas alertas_tematicas_seccion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas_tematicas
    ADD CONSTRAINT alertas_tematicas_seccion_id_fkey FOREIGN KEY (seccion_id) REFERENCES public.secciones(id) ON DELETE CASCADE;


--
-- Name: configuracion_alertas configuracion_alertas_dimension_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_alertas
    ADD CONSTRAINT configuracion_alertas_dimension_id_fkey FOREIGN KEY (dimension_id) REFERENCES public.dimensiones_evaluacion(id) ON DELETE SET NULL DEFERRABLE;


--
-- Name: contenidos contenidos_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contenidos
    ADD CONSTRAINT contenidos_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: criterios_indicadores criterios_indicadores_contenido_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.criterios_indicadores
    ADD CONSTRAINT criterios_indicadores_contenido_id_fkey FOREIGN KEY (contenido_id) REFERENCES public.contenidos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: criterios_indicadores criterios_indicadores_dimension_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.criterios_indicadores
    ADD CONSTRAINT criterios_indicadores_dimension_id_fkey FOREIGN KEY (dimension_id) REFERENCES public.dimensiones_evaluacion(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: detalle_evaluacion detalle_evaluacion_criterio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion
    ADD CONSTRAINT detalle_evaluacion_criterio_id_fkey FOREIGN KEY (criterio_id) REFERENCES public.criterios_indicadores(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: detalle_evaluacion detalle_evaluacion_escala_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion
    ADD CONSTRAINT detalle_evaluacion_escala_id_fkey FOREIGN KEY (escala_id) REFERENCES public.escalas_valoracion(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: detalle_evaluacion detalle_evaluacion_evaluacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion
    ADD CONSTRAINT detalle_evaluacion_evaluacion_id_fkey FOREIGN KEY (evaluacion_id) REFERENCES public.evaluaciones(id) ON DELETE CASCADE DEFERRABLE;


--
-- Name: detalle_evaluacion_saber detalle_evaluacion_saber_eje_tematico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion_saber
    ADD CONSTRAINT detalle_evaluacion_saber_eje_tematico_id_fkey FOREIGN KEY (eje_tematico_id) REFERENCES public.ejes_tematicos(id) ON DELETE RESTRICT;


--
-- Name: detalle_evaluacion_saber detalle_evaluacion_saber_evaluacion_saber_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalle_evaluacion_saber
    ADD CONSTRAINT detalle_evaluacion_saber_evaluacion_saber_id_fkey FOREIGN KEY (evaluacion_saber_id) REFERENCES public.evaluaciones_saber(id) ON DELETE CASCADE;


--
-- Name: ejes_tematicos ejes_tematicos_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos
    ADD CONSTRAINT ejes_tematicos_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id) ON DELETE RESTRICT;


--
-- Name: ejes_tematicos_niveles ejes_tematicos_niveles_eje_tematico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos_niveles
    ADD CONSTRAINT ejes_tematicos_niveles_eje_tematico_id_fkey FOREIGN KEY (eje_tematico_id) REFERENCES public.ejes_tematicos(id) ON DELETE CASCADE;


--
-- Name: ejes_tematicos_niveles ejes_tematicos_niveles_nivel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos_niveles
    ADD CONSTRAINT ejes_tematicos_niveles_nivel_id_fkey FOREIGN KEY (nivel_id) REFERENCES public.niveles(id) ON DELETE CASCADE;


--
-- Name: ejes_tematicos ejes_tematicos_tipo_saber_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ejes_tematicos
    ADD CONSTRAINT ejes_tematicos_tipo_saber_id_fkey FOREIGN KEY (tipo_saber_id) REFERENCES public.tipos_saber(id) ON DELETE RESTRICT;


--
-- Name: email_tokens email_tokens_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_tokens
    ADD CONSTRAINT email_tokens_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: evaluaciones evaluaciones_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT evaluaciones_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: evaluaciones evaluaciones_periodo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT evaluaciones_periodo_id_fkey FOREIGN KEY (periodo_id) REFERENCES public.periodos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: evaluaciones_saber evaluaciones_saber_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones_saber evaluaciones_saber_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones_saber evaluaciones_saber_periodo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_periodo_id_fkey FOREIGN KEY (periodo_id) REFERENCES public.periodos(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones_saber evaluaciones_saber_seccion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_seccion_id_fkey FOREIGN KEY (seccion_id) REFERENCES public.secciones(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones_saber evaluaciones_saber_tipo_saber_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_tipo_saber_id_fkey FOREIGN KEY (tipo_saber_id) REFERENCES public.tipos_saber(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones_saber evaluaciones_saber_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_saber
    ADD CONSTRAINT evaluaciones_saber_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- Name: evaluaciones evaluaciones_seccion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT evaluaciones_seccion_id_fkey FOREIGN KEY (seccion_id) REFERENCES public.secciones(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: evaluaciones evaluaciones_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones
    ADD CONSTRAINT evaluaciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: matriculas matriculas_anio_lectivo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matriculas
    ADD CONSTRAINT matriculas_anio_lectivo_id_fkey FOREIGN KEY (anio_lectivo_id) REFERENCES public.anios_lectivos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: matriculas matriculas_estudiante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matriculas
    ADD CONSTRAINT matriculas_estudiante_id_fkey FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: matriculas matriculas_seccion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matriculas
    ADD CONSTRAINT matriculas_seccion_id_fkey FOREIGN KEY (seccion_id) REFERENCES public.secciones(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: periodos periodos_anio_lectivo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periodos
    ADD CONSTRAINT periodos_anio_lectivo_id_fkey FOREIGN KEY (anio_lectivo_id) REFERENCES public.anios_lectivos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: registro_auditoria registro_auditoria_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro_auditoria
    ADD CONSTRAINT registro_auditoria_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL DEFERRABLE;


--
-- Name: secciones secciones_anio_lectivo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT secciones_anio_lectivo_id_fkey FOREIGN KEY (anio_lectivo_id) REFERENCES public.anios_lectivos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: secciones secciones_centro_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT secciones_centro_id_fkey FOREIGN KEY (centro_id) REFERENCES public.centros_educativos(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: secciones secciones_docente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT secciones_docente_id_fkey FOREIGN KEY (docente_id) REFERENCES public.usuarios(id) ON DELETE SET NULL DEFERRABLE;


--
-- Name: secciones secciones_nivel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secciones
    ADD CONSTRAINT secciones_nivel_id_fkey FOREIGN KEY (nivel_id) REFERENCES public.niveles(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: tokens_refresh tokens_refresh_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_refresh
    ADD CONSTRAINT tokens_refresh_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE DEFERRABLE;


--
-- Name: usuario_materias usuario_materias_materia_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_materias
    ADD CONSTRAINT usuario_materias_materia_id_fkey FOREIGN KEY (materia_id) REFERENCES public.materias(id) ON DELETE CASCADE;


--
-- Name: usuario_materias usuario_materias_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_materias
    ADD CONSTRAINT usuario_materias_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: usuarios usuarios_rol_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE RESTRICT DEFERRABLE;


--
-- Name: usuarios_secciones usuarios_secciones_seccion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_secciones
    ADD CONSTRAINT usuarios_secciones_seccion_id_fkey FOREIGN KEY (seccion_id) REFERENCES public.secciones(id) ON DELETE CASCADE DEFERRABLE;


--
-- Name: usuarios_secciones usuarios_secciones_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_secciones
    ADD CONSTRAINT usuarios_secciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE DEFERRABLE;


--
-- PostgreSQL database dump complete
--


